#!/bin/bash

defaults write org.R-project.R NSAppSleepDisabled -bool YES

export APPDIR=$(cd "$(dirname "$0")"; cd ../..; pwd -P)
echo $APPDIR

open -a R "$APPDIR"

osascript -e 'tell application \"System Events\" to set visible of application process \"R\" to false'
